{% set name = "nvidia-ml-py" %}
{% set version = "11.470.66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20fff0dcd40b32fdc674cd98bc614bb8b6cc8d488687a55bf8c569eef39541f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
  run_constrained:
    # Packages that conflict with nvidia-ml-py
    # Both packages install pynvml.py
    - nvidia-ml ==9999999999
    - pynvml ==9999999999

test:
  imports:
    - pynvml
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.nvidia.com
  summary: Python Bindings for the NVIDIA Management Library
  license: BSD-3-Clause
  license_family: BSD
  license_file: README.txt
  dev_url: https://developer.nvidia.com/nvidia-management-library-nvml
  doc_url: https://docs.nvidia.com/deploy/nvml-api/index.html

extra:
  recipe-maintainers:
    - XuehaiPan
