{% set name = "nvidia-ml-py" %}
{% set version = "12.560.30" %}
{% set major_version = version.split(".")[0]|int %}
{% set sha256 = "f0254dc7400647680a072ee02509bfd46102b60bdfeca321576d4d4817e7fe97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
  run_constrained:
    # Packages that conflict with nvidia-ml-py
    # Both packages install pynvml.py
    - nvidia-ml ==9999999999
    - pynvml ~={{ major_version }}.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pynvml
  commands:
    - pip check

about:
  home: http://www.nvidia.com
  summary: Python Bindings for the NVIDIA Management Library
  license: BSD-3-Clause
  license_family: BSD
  license_file: README.txt
  dev_url: https://developer.nvidia.com/nvidia-management-library-nvml
  doc_url: https://docs.nvidia.com/deploy/nvml-api/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - XuehaiPan
